### ISSUE TITLE
Dialoge

### ISSUE THREAD

**Issue by NewLordVile** [ariogato/Koramu#45]
Der Spieler soll mit den, in #44 implementierten, "NPC"s "kommunizieren" können. Bei einem Ansprechen (Interaktionstaste), soll die Möglichkeit bestehen einen Dialog auslösen zu können.

Es gibt mehrere Möglichkeiten, dies zu implementieren. Eine Lösung wäre, einen neuen Spielzustand, den `dialogState` zu implementieren. 
Eine schönere Lösung wäre: eine Klasse zu implementieren, die sobald sie instanziiert wird, eine Dialogbox erstellt und den Objekten, die sich nicht mehr bewegen sollen, einen Befehl (Klasse die von `BaseCommand` erbt) zuteilt, der sie davon abhält sich zu bewegen.

Die Dialogbox soll immer einen Text bis zu einem bestimmten Zeichen enthalten (wahrscheinlich '\n'), bis die Interaktionstaste gedrückt wird. Diese soll den Dialog beenden, falls kein Text mehr übrig ist, oder den nächsten Text (ab dem letzten '\n') anzeigen. 

Zuletzt soll es Lua Skripten möglich sein Objekte dieser Klasse erstellen zu können.

**Comment by ariogato** [comment]
Das Ticket wird durch die Interaktionsmethode aus #44 vorerst überflüssig. Glaube ich zumindest 😆
